import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./providers/theme-provider";
import { AlertProvider } from "./providers/alert-provider";
import { ModeToggle } from "../components/ui/theme-button/modeToggle";
import { DataProvider } from "./context/dataContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AlertProvider>
            <DataProvider>
              {children}
              <div className="fixed right-0 bottom-0 m-4 z-100">
                <ModeToggle />
              </div>
            </DataProvider>
          </AlertProvider>
        </ThemeProvider>
      </body>
    </html >
  );
}
